import { Nullable } from 'quidproquo-core';

import fs from 'fs';
import path from 'path';

import { DEV_SERVER_PUBLIC_FILE_STORAGE_PORT_ENV, DEV_SERVER_PUBLIC_HOST_ENV } from '../../lib/devServerEntry';
import { Mount } from './parseMounts';
import { PortMapping } from './parsePortMappings';

export type ComposeFileOptions = {
  contextDir: string;
  imageName: string;
  serviceName: string;
  volumeName: string;
  portMappings: PortMapping[];
  // Host directory for the app's state; null keeps it in the named volume.
  dataPath: Nullable<string>;
  // Host folders the app reads or writes beyond its state.
  mounts: Mount[];
  // The address browsers use for the host; null leaves secure file urls on localhost.
  publicHost: Nullable<string>;
  // Host-side port of the file storage listener, for the secure urls it hands out.
  publicFileStoragePort: number;
};

/**
 * A docker-compose.yml for running the image on any docker host: the image, the port mappings
 * the frontend was built for, the public host, where the app's state lives, and any other host
 * folders mounted into it. Returns its path.
 */
export const writeComposeFile = ({
  contextDir,
  imageName,
  serviceName,
  volumeName,
  portMappings,
  dataPath,
  mounts,
  publicHost,
  publicFileStoragePort,
}: ComposeFileOptions): string => {
  const ports = portMappings.map((mapping) => `      - "${mapping.host}:${mapping.container}"`).join('\n');

  const environmentLines = [
    ...(publicHost ? [`${DEV_SERVER_PUBLIC_HOST_ENV}=${publicHost}`] : []),
    `${DEV_SERVER_PUBLIC_FILE_STORAGE_PORT_ENV}=${publicFileStoragePort}`,
  ];
  const environment = `    environment:\n${environmentLines.map((line) => `      - ${line}`).join('\n')}\n`;

  // All app state (key-value stores, file storage) is this one directory.
  const stateSource = dataPath ?? volumeName;
  const namedVolume = dataPath ? '' : `\nvolumes:\n  ${volumeName}:\n`;
  // Quoted (a JSON string is a valid YAML one), since host folders can hold spaces.
  const mountLines = mounts.map((mount) => `\n      - ${JSON.stringify(`${mount.host}:${mount.container}${mount.readOnly ? ':ro' : ''}`)}`).join('');

  const compose = `# Generated by qpq go from deploy.config.json. Host ports are baked into the frontend, so
# change them there and rebuild rather than here.
services:
  ${serviceName}:
    image: ${imageName}
    container_name: ${serviceName}
    restart: unless-stopped
${environment}    ports:
${ports}
    volumes:
      - ${stateSource}:/app/.qpq-runtime${mountLines}
${namedVolume}`;

  const composePath = path.join(contextDir, 'docker-compose.yml');
  fs.writeFileSync(composePath, compose);
  return composePath;
};
