import { Nullable } from 'quidproquo-core';

import fs from 'fs';
import path from 'path';

import { DEV_SERVER_PUBLIC_HOST_ENV } from '../../lib/devServerEntry';
import { PortMapping } from './parsePortMappings';

export type ComposeFileOptions = {
  contextDir: string;
  imageName: string;
  serviceName: string;
  volumeName: string;
  portMappings: PortMapping[];
  // Host directory for the app's state; null keeps it in the named volume.
  dataPath: Nullable<string>;
  // The address browsers use for the host; null leaves secure file urls on localhost.
  publicHost: Nullable<string>;
};

/**
 * A docker-compose.yml for running the image on any docker host: the image, the port mappings
 * the frontend was built for, the public host, and where the app's state lives. Returns its path.
 */
export const writeComposeFile = ({
  contextDir,
  imageName,
  serviceName,
  volumeName,
  portMappings,
  dataPath,
  publicHost,
}: ComposeFileOptions): string => {
  const ports = portMappings.map((mapping) => `      - "${mapping.host}:${mapping.container}"`).join('\n');

  const environment = publicHost ? `    environment:\n      - ${DEV_SERVER_PUBLIC_HOST_ENV}=${publicHost}\n` : '';

  // All app state (key-value stores, file storage) is this one directory.
  const stateSource = dataPath ?? volumeName;
  const namedVolume = dataPath ? '' : `\nvolumes:\n  ${volumeName}:\n`;

  const compose = `# Generated by qpq go from deploy.config.json. Host ports are baked into the frontend, so
# change them there and rebuild rather than here.
services:
  ${serviceName}:
    image: ${imageName}
    container_name: ${serviceName}
    restart: unless-stopped
${environment}    ports:
${ports}
    volumes:
      - ${stateSource}:/app/.qpq-runtime
${namedVolume}`;

  const composePath = path.join(contextDir, 'docker-compose.yml');
  fs.writeFileSync(composePath, compose);
  return composePath;
};
