import fs from 'fs';
import path from 'path';

import { DEFAULT_DEV_SERVER_PORTS, getDevServerConfigPath } from './devServerPorts';

/**
 * What the generated bootstrap does: serve forever, run pending migrations once and exit, or
 * both in turn (the docker image, where nothing else ever deploys and so nothing else would
 * run the migrations).
 */
export type DevServerEntryMode = 'serve' | 'migrate' | 'migrate-then-serve';

/** Env vars the docker image sets so the running server knows how the outside world reaches it. */
export const DEV_SERVER_PUBLIC_HOST_ENV = 'QPQ_PUBLIC_HOST';
export const DEV_SERVER_PUBLIC_FILE_STORAGE_PORT_ENV = 'QPQ_PUBLIC_FILE_STORAGE_PORT';

const ENTRY_FILE_NAMES: Record<DevServerEntryMode, string> = {
  serve: 'entry.ts',
  migrate: 'migrate.entry.ts',
  'migrate-then-serve': 'entry.ts',
};

const reportMigrations = `(ran) => {
    const total = Object.values(ran).reduce((sum, keys) => sum + keys.length, 0);
    for (const [service, keys] of Object.entries(ran)) {
      for (const key of keys) {
        console.log(\` [\${service}] \${key}\`);
      }
    }
    console.log(total === 0 ? 'No pending migrations.' : \`Ran \${total} migration(s).\`);
  }`;

const getRunCall = (mode: DevServerEntryMode): string => {
  if (mode === 'serve') {
    return 'startDevServer(devServerConfig, devServerConfigOverrides);';
  }

  const afterMigrations = mode === 'migrate' ? 'process.exit(0);' : 'return startDevServer(devServerConfig, devServerConfigOverrides);';

  return `runMigrations(devServerConfig, devServerConfigOverrides)
  .then(${reportMigrations})
  .then(() => {
    ${afterMigrations}
  })
  .catch((error) => {
    console.error('Migration failed:', error);
    // Non-zero so CI, shell chains and a container restart policy actually notice.
    process.exit(1);
  });`;
};

/**
 * Writes the dev-server bootstrap for an app and returns its path. Generated per build so it
 * can import the optional app-owned overrides file (apps/<app>/devServer.config.ts) and the
 * `quidproquo-dynamic-loader` virtual module QpqPlugin injects at bundle time. Every mode
 * shares one bundle shape, so a local migration run rehearses exactly the deployed path.
 */
export const writeDevServerEntry = (root: string, appName: string, mode: DevServerEntryMode = 'serve'): string => {
  const entryDir = path.join(root, 'dist', 'qpq', 'dev-server');
  const entryPath = path.join(entryDir, ENTRY_FILE_NAMES[mode]);

  const overridesPath = getDevServerConfigPath(appName);
  const overridesImport = fs.existsSync(overridesPath)
    ? `import devServerConfigOverrides from ${JSON.stringify(overridesPath.replace(/\.ts$/, ''))};`
    : 'const devServerConfigOverrides = {};';

  const imports = mode === 'serve' ? 'startDevServer' : mode === 'migrate' ? 'runMigrations' : 'runMigrations, startDevServer';

  fs.mkdirSync(entryDir, { recursive: true });
  fs.writeFileSync(
    entryPath,
    `// GENERATED by qpq — do not edit.
import { ${imports} } from 'quidproquo-dev-server';
import {
  qpqConfigs,
  qpqDynamicModuleLoaderForService,
  // @ts-ignore - Special build-time virtual module
} from 'quidproquo-dynamic-loader';

${overridesImport}

// Ports are defaults here; the app's devServer.config.ts \`ports\` win when the server resolves its config.
const devServerConfig = {
  serverDomain: 'localhost',
  serverPort: ${DEFAULT_DEV_SERVER_PORTS.api},
  webSocketPort: ${DEFAULT_DEV_SERVER_PORTS.webSocket},
  // Scoped per app so running the dev server for two apps out of the same
  // repo root doesn't share kvs/file-storage/config state.
  runtimePath: ${JSON.stringify(path.join('.qpq-runtime', appName))},
  fileStorageConfig: {
    // Secure file urls are absolute, so a container has to be told the address browsers use.
    secureUrlHost: process.env.${DEV_SERVER_PUBLIC_HOST_ENV} || 'localhost',
    secureUrlPort: ${DEFAULT_DEV_SERVER_PORTS.fileStorage},
    secureUrlPublicPort: Number(process.env.${DEV_SERVER_PUBLIC_FILE_STORAGE_PORT_ENV}) || undefined,
    secureUrlSecret: 'dev-secure-url-secret',
  },
  qpqConfigs,
  dynamicModuleLoader: qpqDynamicModuleLoaderForService,
  // QPQ_WEB_ROOT (set in the docker platform image) turns on static web serving.
  webRoot: process.env.QPQ_WEB_ROOT,
  logServiceName: 'admin',
  delay: { default: 0 },
};

${getRunCall(mode)}
`,
  );

  return entryPath;
};
