export enum AiModel {
  ClaudeHaiku35 = 'claude-3-5-haiku',
  ClaudeSonnet35 = 'claude-3-5-sonnet',
  ClaudeSonnet4 = 'claude-sonnet-4',
  ClaudeOpus4 = 'claude-opus-4',
  ClaudeHaiku45 = 'claude-haiku-4-5',
  ClaudeSonnet45 = 'claude-sonnet-4-5',
  ClaudeOpus45 = 'claude-opus-4-5',
  ClaudeSonnet46 = 'claude-sonnet-4-6',
  ClaudeOpus46 = 'claude-opus-4-6',
  ClaudeOpus47 = 'claude-opus-4-7',
  ClaudeOpus48 = 'claude-opus-4-8',
  ClaudeSonnet5 = 'claude-sonnet-5',
  ClaudeOpus5 = 'claude-opus-5',
  ClaudeOpus55 = 'claude-opus-5-5',
}
